spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb+srv://gijin22:${DATABASE_PASSWORD}@cluster0.uwirm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: portmate
    redis:
      host: localhost
      port: 6379
      password: 1234
      timeout: 6000ms

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


  jackson:
    time-zone: Asia/Seoul

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      properties:
        max.in.flight.requests.per.connection: 1
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 300000
    listener:
      ack-mode: record
      missing-topics-fatal: false
    admin:
      properties:
        bootstrap.servers: kafka:9092
    properties:
      auto.create.topics.enable: true
      default.replication.factor: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1



#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: project.doctalk@gmail.com
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          ssl:
#            enable: false
#      debug: true
#

jwt:
  issuer: project.doctalk@gmail.com
  secret: "jfsgkhdsjkweoiruwqejkrfbhnsadkjlfghbwerqewrsdfgdsfagbdf"
  access-expiration: 3600
  refresh-expiration: 8640

server:
  port: 8080
  address: 0.0.0.0
  max-http-header-size: 16KB
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024 # 1KB ??? ??? ?? ??


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: WARN


springdoc:
  default-produces-media-type: application/json
  override-with-generic-response: false


firebase:
  json: ${FIREBASE_JSON}