name: GCP Artifact Registry 자동 배포

on:
  push:
    branches:
      - test

env:
  REGION: us-central1
  IMAGE_NAME: portmate-server
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPO_NAME: ${{ secrets.ARTIFACT_REPO }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: JAR 빌드
        run: ./gradlew clean bootJar -x test

      - name: JAR 파일 확인
        run: |
          echo "JAR 파일 존재 여부 확인 중..."
          ls -la build/libs/
          if [ ! -f build/libs/PortMate-0.0.1-SNAPSHOT.jar ]; then
            echo "JAR 파일을 찾을 수 없습니다."
            exit 1
          fi
          echo "JAR 파일 확인 완료"

      - name: GCP 인증
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Docker 인증 구성
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet


      - name: Docker 이미지 빌드 및 푸시
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest"
          echo "이미지 빌드 중: $IMAGE"
          docker build -t $IMAGE .
          echo "Artifact Registry로 이미지 푸시 중..."
          docker push $IMAGE
          echo "이미지 푸시 완료"

      - name: VM 서버 배포
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo '${{ secrets.GCP_SA_KEY }}' > gcp_sa_key.json
            cat gcp_sa_key.json | sudo docker login -u _json_key --password-stdin https://${{ env.REGION }}-docker.pkg.dev
            cd /home/${{ secrets.VM_USER }}/portmate
            sudo docker compose pull
            sudo docker compose down
            FIREBASE_JSON='${{ secrets.FIREBASE_JSON }}' sudo -E docker compose up -d
            rm -f gcp_sa_key.json
            echo "배포 완료"
      
